version: '3'

services:
  db:
    build: ./db/
    ports: #- HOST:CONTAINER'
      - '3000:3306' # expose ports
    expose:
      - '3306'
    environment:
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=password
    # healthcheck:
    #   test: 'exit 0'
    networks:
      - services
  blast-service:
    container_name: blast-service
    build: ./service/
    command: nodemon server.js
    volumes:
      - './service:/usr/src/'
      - './service/package.json:/usr/src/package.json'
    ports: #- HOST:CONTAINER'
      - '3001:80' # expose ports
    expose:
      - '80'
    env_file:
      - ./service/.env
    networks:
      - services
networks:
  services:
    driver: bridge
